### ISSUE TITLE
Output Within Terminal Whenever PHP School is run. 

### ISSUE THREAD

**Issue by w4nt** [php-school/workshop-manager#24]
Whenever workshop-manager with associated arguments or any of the associated modules (learnyouphp, php7way, callable functions) is run, instead of the command executing without posting any output to the screen, it seems to run in a verbose manner. 

Attached is a text file showing the output that appears. The output does not seem to hinder the application running in any manner. 

The OS I'm running is Debian Testing with the KDE Plasma Desktop. I had fully upgraded to the latest version of Testing at the time of submitting the issue. 

[workshop_manager_output.txt](https://github.com/php-school/workshop-manager/files/724396/workshop_manager_output.txt)

**Comment by AydinHassan** [comment]
That's really bizarre - it doesn't even look like PHP output - is there anyway you could setup a reproduce environment maybe? Using docker or something?

**Comment by w4nt** [comment]
Hmmm... I _could_ try using a VM and see if the issue is unique. Which distros should I try? Or are you referring to setting up a reproduce environment specifically for Debian?

**Comment by mikeymike** [comment]
Hey @w4nt are you still experiencing this or found a work around. I think @AydinHassan was wondering if you could create us a mirror of your env with docker/vagrant that we could spin up and reproduce.

**Comment by w4nt** [comment]
@mikeymike @AydinHassan Sorry about the silence. Have been busy. Yes I still experience the issue. Its not a problem per se, since I'm used to weird things happening and all, but if you'd like it fixed I'd be glad to assist. Just ran `workshop-manager self-update` which I think should take care of the updates in general and I _have_ updated my machine in the intervening period since. 

I have never used docker or vagrant so I wouldn't know where to begin doing that.

**Comment by w4nt** [comment]
@mikeymike @AydinHassan Issue seems to have gone by itself. This issue maybe closed.

**Comment by AydinHassan** [comment]
Thanks for the update
