### ISSUE TITLE
False error "... not running in a Unix environment"

### ISSUE THREAD

**Issue by fridde** [php-school/workshop-manager#26]
I run a Cygwin bash on ConEmu and has been working flawlessly for a few years.

After installing ```php-school/workshop-manager``` via composer, I try running the workshop manager and get the error message specified [here](https://github.com/php-school/workshop-manager/blob/master/app/bootstrap.php#L39).

That's not very helpful. Using the ```DIRECTORY_SEPARATOR``` is not a valid way of determining if I'm in cygwin or not.

Is it relevant that I'm using a XAMPP component as my php executable?

**Comment by AydinHassan** [comment]
We used the same check as symfony/console and it worked with our tests. See https://github.com/symfony/console/blob/19b068288ea88d3a0d787fa63622b8d012664c59/Output/StreamOutput.php#L93 which looks like DIRECTORY_SEPARATOR should be \. However I don't have access to a windows machine, nor any machine for the next few weeks. @mikeymike you had this running with that setup fine didn't you?

**Comment by AydinHassan** [comment]
Sorry the formatting is a bit borked on my phone

**Comment by mikeymike** [comment]
Hey .. yeah i had this working on a Windows 10 tablet which is how we got to this workflow with windows ... The only time i got this error was when the console was not using the Unix environment configuration but it sounds like you already have that setup so I'm not sure why it would still not be working 

Alternatively we have a [docker setup](https://github.com/php-school/docker-phpschool) with the hope there being able to make it cross platform really easily. 

I'm also on holiday atm and won't have access to a Windows machine until mid next week at the earliest ... I hope your able to get it running and would love some more feedback from a Windows user as we both have limited access to that platform
