### ISSUE TITLE
Getting error when running "workshop-manager verify" in arch linux

### ISSUE THREAD

**Issue by puranjaymohan** [php-school/workshop-manager#29]
I get the following error when i run "workshop-manager verify",
 
**php: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory**

please find a solution

thanks.

**Comment by AydinHassan** [comment]
Hi @puranjaymohan this sounds like your php installation is broken, I don't think this is related to `workshop-manager`. I doubt there is anything we can do to fix that.

**Comment by puranjaymohan** [comment]
i just installed latest version of php.
can you help me with troubleshooting

**Comment by puranjaymohan** [comment]
If possible , How to run this on windows. 
I want to do the PHP school workshops, but linux is not working .

**Comment by mikeymike** [comment]
it would be difficult to help troubleshoot as we're not running on the same platform, I'd recommend posting on an Arch Linux forum or IRC channel where they'd understand the platform. 

Windows has it's own set of hoops that makes installation difficult, you can try using Cygwin and ConEmu to get it going natively in Windows (https://phpschool.io/install#windows) or alternatively if you can use docker you can try the instructions from https://github.com/php-school/docker-phpschool which we've had success with on Windows. 

Hope you manage to get it up and running 🤞

**Comment by puranjaymohan** [comment]
Thanks @mikeymike 
I was able to setup php-school on windows using cygwin .
thanks once again

**Comment by mikeymike** [comment]
awesome have fun !
