### ISSUE TITLE
Cannot install php-school

### ISSUE THREAD

**Issue by qir4ni** [php-school/workshop-manager#35]
Changed current directory to C:/Users/qiran/AppData/Roaming/Composer
Using version ^1.1 for php-school/workshop-manager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-school/workshop-manager ^1.1 -> satisfiable by php-school/workshop-manager[1.1.0].
    - Conclusion: remove symfony/console v4.2.8
    - Conclusion: don't install symfony/console v4.2.8
    - php-school/workshop-manager 1.1.0 requires symfony/console ^3.0 -> satisfiable by symfony/console[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/console[v3.0.0, v4.2.8].
    - Can only install one of: symfony/console[v3.0.1, v4.2.8].
    - Can only install one of: symfony/console[v3.0.2, v4.2.8].
    - Can only install one of: symfony/console[v3.0.3, v4.2.8].
    - Can only install one of: symfony/console[v3.0.4, v4.2.8].
    - Can only install one of: symfony/console[v3.0.5, v4.2.8].
    - Can only install one of: symfony/console[v3.0.6, v4.2.8].
    - Can only install one of: symfony/console[v3.0.7, v4.2.8].
    - Can only install one of: symfony/console[v3.0.8, v4.2.8].
    - Can only install one of: symfony/console[v3.0.9, v4.2.8].
    - Can only install one of: symfony/console[v3.1.0, v4.2.8].
    - Can only install one of: symfony/console[v3.1.1, v4.2.8].
    - Can only install one of: symfony/console[v3.1.10, v4.2.8].
    - Can only install one of: symfony/console[v3.1.2, v4.2.8].
    - Can only install one of: symfony/console[v3.1.3, v4.2.8].
    - Can only install one of: symfony/console[v3.1.4, v4.2.8].
    - Can only install one of: symfony/console[v3.1.5, v4.2.8].
    - Can only install one of: symfony/console[v3.1.6, v4.2.8].
    - Can only install one of: symfony/console[v3.1.7, v4.2.8].
    - Can only install one of: symfony/console[v3.1.8, v4.2.8].
    - Can only install one of: symfony/console[v3.1.9, v4.2.8].
    - Can only install one of: symfony/console[v3.2.0, v4.2.8].
    - Can only install one of: symfony/console[v3.2.1, v4.2.8].
    - Can only install one of: symfony/console[v3.2.10, v4.2.8].
    - Can only install one of: symfony/console[v3.2.11, v4.2.8].
    - Can only install one of: symfony/console[v3.2.12, v4.2.8].
    - Can only install one of: symfony/console[v3.2.13, v4.2.8].
    - Can only install one of: symfony/console[v3.2.14, v4.2.8].
    - Can only install one of: symfony/console[v3.2.2, v4.2.8].
    - Can only install one of: symfony/console[v3.2.3, v4.2.8].
    - Can only install one of: symfony/console[v3.2.4, v4.2.8].
    - Can only install one of: symfony/console[v3.2.5, v4.2.8].
    - Can only install one of: symfony/console[v3.2.6, v4.2.8].
    - Can only install one of: symfony/console[v3.2.7, v4.2.8].
    - Can only install one of: symfony/console[v3.2.8, v4.2.8].
    - Can only install one of: symfony/console[v3.2.9, v4.2.8].
    - Can only install one of: symfony/console[v3.3.0, v4.2.8].
    - Can only install one of: symfony/console[v3.3.1, v4.2.8].
    - Can only install one of: symfony/console[v3.3.10, v4.2.8].
    - Can only install one of: symfony/console[v3.3.11, v4.2.8].
    - Can only install one of: symfony/console[v3.3.12, v4.2.8].
    - Can only install one of: symfony/console[v3.3.13, v4.2.8].
    - Can only install one of: symfony/console[v3.3.14, v4.2.8].
    - Can only install one of: symfony/console[v3.3.15, v4.2.8].
    - Can only install one of: symfony/console[v3.3.16, v4.2.8].
    - Can only install one of: symfony/console[v3.3.17, v4.2.8].
    - Can only install one of: symfony/console[v3.3.18, v4.2.8].
    - Can only install one of: symfony/console[v3.3.2, v4.2.8].
    - Can only install one of: symfony/console[v3.3.3, v4.2.8].
    - Can only install one of: symfony/console[v3.3.4, v4.2.8].
    - Can only install one of: symfony/console[v3.3.5, v4.2.8].
    - Can only install one of: symfony/console[v3.3.6, v4.2.8].
    - Can only install one of: symfony/console[v3.3.7, v4.2.8].
    - Can only install one of: symfony/console[v3.3.8, v4.2.8].
    - Can only install one of: symfony/console[v3.3.9, v4.2.8].
    - Can only install one of: symfony/console[v3.4.0, v4.2.8].
    - Can only install one of: symfony/console[v3.4.1, v4.2.8].
    - Can only install one of: symfony/console[v3.4.10, v4.2.8].
    - Can only install one of: symfony/console[v3.4.11, v4.2.8].
    - Can only install one of: symfony/console[v3.4.12, v4.2.8].
    - Can only install one of: symfony/console[v3.4.13, v4.2.8].
    - Can only install one of: symfony/console[v3.4.14, v4.2.8].
    - Can only install one of: symfony/console[v3.4.15, v4.2.8].
    - Can only install one of: symfony/console[v3.4.16, v4.2.8].
    - Can only install one of: symfony/console[v3.4.17, v4.2.8].
    - Can only install one of: symfony/console[v3.4.18, v4.2.8].
    - Can only install one of: symfony/console[v3.4.19, v4.2.8].
    - Can only install one of: symfony/console[v3.4.2, v4.2.8].
    - Can only install one of: symfony/console[v3.4.20, v4.2.8].
    - Can only install one of: symfony/console[v3.4.21, v4.2.8].
    - Can only install one of: symfony/console[v3.4.22, v4.2.8].
    - Can only install one of: symfony/console[v3.4.23, v4.2.8].
    - Can only install one of: symfony/console[v3.4.24, v4.2.8].
    - Can only install one of: symfony/console[v3.4.25, v4.2.8].
    - Can only install one of: symfony/console[v3.4.26, v4.2.8].
    - Can only install one of: symfony/console[v3.4.27, v4.2.8].
    - Can only install one of: symfony/console[v3.4.3, v4.2.8].
    - Can only install one of: symfony/console[v3.4.4, v4.2.8].
    - Can only install one of: symfony/console[v3.4.5, v4.2.8].
    - Can only install one of: symfony/console[v3.4.6, v4.2.8].
    - Can only install one of: symfony/console[v3.4.7, v4.2.8].
    - Can only install one of: symfony/console[v3.4.8, v4.2.8].
    - Can only install one of: symfony/console[v3.4.9, v4.2.8].
    - Installation request for symfony/console (locked at v4.2.8) -> satisfiable by symfony/console[v4.2.8].

Installation failed, reverting ./composer.json to its original content.

**Comment by AydinHassan** [comment]
Hi, looks like maybe you have symfony/console 4 installed globally and our restraints currently require only 3. I’m sure the workshop works with 4 fine. If you’re up to it you can send a PR allowing for 3.x and 4.x. If not I can fix it in a few days. Got a busy schedule so won’t have time until after that 😊

**Comment by AydinHassan** [comment]
Should be fixed now, try upgrading or re-downloading!
