### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by qir4ni** [php-school/workshop-manager#48]
When im trying to run command "workshop-manager verify" i got this

PHP Fatal error:  Uncaught DI\NotFoundException: No entry or class found for 'Composer\IO\IOInterface' in C:\Users\qiran\AppData\Roaming\Composer\vendor\php-di\php-di\src\DI\Container.php:128
Stack trace:
#0 C:\Users\qiran\AppData\Roaming\Composer\vendor\php-school\workshop-manager\app\bootstrap.php(37): DI\Container->get('Composer\\IO\\IOI...')
#1 C:\Users\qiran\AppData\Roaming\Composer\vendor\php-school\workshop-manager\bin\workshop-manager(4): require('C:\\Users\\qiran\\...')
#2 {main}
  thrown in C:\Users\qiran\AppData\Roaming\Composer\vendor\php-di\php-di\src\DI\Container.php on line 128

Fatal error: Uncaught DI\NotFoundException: No entry or class found for 'Composer\IO\IOInterface' in C:\Users\qiran\AppData\Roaming\Composer\vendor\php-di\php-di\src\DI\Container.php:128
Stack trace:
#0 C:\Users\qiran\AppData\Roaming\Composer\vendor\php-school\workshop-manager\app\bootstrap.php(37): DI\Container->get('Composer\\IO\\IOI...')
#1 C:\Users\qiran\AppData\Roaming\Composer\vendor\php-school\workshop-manager\bin\workshop-manager(4): require('C:\\Users\\qiran\\...')
#2 {main}
  thrown in C:\Users\qiran\AppData\Roaming\Composer\vendor\php-di\php-di\src\DI\Container.php on line 128

**Comment by AydinHassan** [comment]
Hmm. Are you running from source? Did you clone recently? Like in the last 12 hours? Because I made a bunch of changes. I may have broke something? Also are you running on Windows because we don’t actually support windows 😪

**Comment by AydinHassan** [comment]
Ah yeah. It looks like this part of the code hasn't ran in a while and got out of sync. https://github.com/php-school/workshop-manager/blob/master/app/bootstrap.php#L37

**Comment by AydinHassan** [comment]
Actually @qiraniawis I think you have a really old version, this was fixed ages ago: https://github.com/php-school/workshop-manager/commit/ca907e405155bdaf2223861cbbaa861833bf2b96#diff-52787cc3750ff1375665915b961be8c9. But yeah it doesn't work on Windows.
