### ISSUE TITLE
Class not found at "workshop-manager verify"

### ISSUE THREAD

**Issue by nisalb** [php-school/workshop-manager#49]
I just downloaded `workshop-manager.phar` as per instructions given at the official site. But when it try to execute `verify` command it gives me this error:

```
PHP Warning:  Class 'Tightenco\Collect\Support\Arr' not found in phar:///usr/local/bin/workshop-manager/vendor/tightenco/collect/src/Collect/Support/alias.php on line 16

PHP Parse error:  syntax error, unexpected '=' in phar:///usr/local/bin/workshop-manager/vendor/tightenco/collect/src/Collect/Support/Arr.php on line 380
```

My PHP version is:

```
PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies
```

My OS is Debian 9.9

**Comment by mikeymike** [comment]
Hey @koolify I believe we did just bump the PHP requirement to >=7.1 as 7.0 is now end of life. 

Looking at the code I'm fairly sure if you upgrade your PHP version this error should go away, let us know if it doesn't though!

**Comment by AydinHassan** [comment]
Hmm yeah sorry. I didn't update the website with the minimum requirements, will do that now.

**Comment by AydinHassan** [comment]
I've updated the site now, sorry for the confusion @koolify !
