### ISSUE TITLE
Better help command output

### ISSUE THREAD

**Issue by AydinHassan** [php-school/workshop-manager#7]
Add more detail about each command and how to use it.

This would be accomplished here: https://github.com/php-school/workshop-manager/blob/master/app/config.php#L39

A reference for good detail is: https://github.com/symfony/console/blob/master/Command/HelpCommand.php#L44

**Comment by nbezzala** [comment]
Can you please give me the reference for good detail? Looks like it is the same as the one to be changed.

**Comment by AydinHassan** [comment]
Hi @nbezzala - indeed a c+p error, I've updated the issue :)

**Comment by AydinHassan** [comment]
Being handled by #30 !
